-- PostgreSQL Production Database Schema for Arjuna IT Services
-- Domain Architecture: TaskFlow Project & Leave Management (project_management)
-- Generated by BizzMitra AI Engine
-- Problem Statement Reference:
-- "Project managers often set and track task deadlines without factoring in employee leave, so a deadline gets fixed without knowing whether the assigned person will actually be available for the full task duration. This gap means there's no built-in buffer or handover preparation when someone goes on leave mid-task — work simply stalls or gets rushed at the last minute because the leave was never factored into how the deadline was structured in the first place, rather than being planned around from the start."

CREATE TABLE IF NOT EXISTS public.project_management_records (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  col1_data TEXT NOT NULL, -- Semantic Mapping: Assigned Team Member
  col2_data TEXT NOT NULL, -- Semantic Mapping: Scheduled Duration
  status TEXT NOT NULL,    -- Semantic Mapping: Kanban State
  badge TEXT DEFAULT 'Active',
  assignee TEXT NOT NULL,  -- Semantic Mapping: Task Owner
  metric_value TEXT NOT NULL, -- Semantic Mapping: Leave Overlap Status
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.project_management_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for demo application"
  ON public.project_management_records
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Team and Role Authentication table
CREATE TABLE IF NOT EXISTS public.project_management_users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  badge TEXT NOT NULL,
  department TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.project_management_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read-write for authenticated users"
  ON public.project_management_users
  FOR ALL
  USING (true)
  WITH CHECK (true);
